# Generated by Django 5.2.3 on 2025-06-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite')], max_length=20),
        ),
    ]
